---

- name: Update apt-cache
  apt: update_cache=yes 

- name: install libwebsocket dependencies
  apt: name=cmake state=latest

- name: check out libwebsockets
  git: repo=https://github.com/warmcat/libwebsockets.git
    dest=/usr/local/src/freeswitch/libs/libwebsockets
    version=v3.1.0
    depth=50
    accept_hostkey=yes
    force=yes

- name: create build directory
  file:
    path: /usr/local/src/freeswitch/libs/libwebsockets/build
    state: directory

- name: build libwebsockets
  shell: cmake .. && make && make install
  args:
    chdir: /usr/local/src/freeswitch/libs/libwebsockets/build

- name: patch configure.ac
  patch:
    src: configure.ac.lws.patch
    dest: "{{freeswitch_sources_path}}/configure.ac"

- name: patch Makefile.am
  patch:
    src: Makefile.am.lws.patch
    dest: "{{freeswitch_sources_path}}/Makefile.am"

- name: bootstrap 
  shell: ./bootstrap.sh -j chdir={{freeswitch_sources_path}}

- name: re-run Freeswitch configuration
  shell: ./{{freeswitch_configure_command}} --with-grpc=yes --with-lws=yes
  args:
    chdir: "{{freeswitch_sources_path}}"

- name: re-run FreeSwitch make
  shell: make chdir={{freeswitch_sources_path}}

- name: re-run FreeSwitch install
  shell: make install chdir={{freeswitch_sources_path}}

