---

- name: check out libwebsockets
  git: repo=https://github.com/warmcat/libwebsockets.git
    dest=/usr/local/src/freeswitch/libs/libwebsockets
    version=v3.1.0
    depth=50
    accept_hostkey=yes
    force=yes

- name: create build directory
  file:
    path: /usr/local/src/freeswitch/libs/libwebsockets/build
    state: directory

- name: build libwebsockets
  shell: cmake .. && make && make install
  args:
    chdir: /usr/local/src/freeswitch/libs/libwebsockets/build


